// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-jobs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-jobs.ts
var MODES = ["vc", "pe", "ib", "mc", "st", "im", "tech", "startups"];
var search_jobs_default = defineTool({
  name: "search_jobs",
  title: "Search jobs",
  description: "Search the MBAJOBSCOUT UK job database by career mode (vc, pe, ib, mc, st, im, tech, startups), keyword and location.",
  inputSchema: {
    mode: z.enum(MODES).default("vc").describe("Career category to search."),
    query: z.string().trim().optional().describe("Keyword matched against job title and company."),
    location: z.string().trim().optional().describe("Location filter, e.g. 'London' or 'Remote'."),
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum number of jobs to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ mode, query, location, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("scraped_jobs").select("title, company, location, salary, source, url, posted_date, scraped_at").eq("mode", mode).order("scraped_at", { ascending: false }).limit(limit);
    if (query) q = q.or(`title.ilike.%${query}%,company.ilike.%${query}%`);
    if (location) q = q.ilike("location", `%${location}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, jobs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tracked-jobs.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_tracked_jobs_default = defineTool2({
  name: "list_tracked_jobs",
  title: "List tracked jobs",
  description: "List jobs the signed-in user has saved, applied to, or marked as not interested.",
  inputSchema: {
    action: z2.enum(["saved", "applied", "not_interested"]).optional().describe("Filter to one tracking status. Omit to return all."),
    limit: z2.number().int().min(1).max(100).default(50).describe("Maximum rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ action, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("job_actions").select("action, job_title, job_company, job_source, job_url, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (action) q = q.eq("action", action);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/track-job.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var track_job_default = defineTool3({
  name: "track_job",
  title: "Track a job",
  description: "Save a job, mark it as applied, or mark it as not interested for the signed-in user.",
  inputSchema: {
    job_url: z3.string().url().describe("Canonical URL of the job listing."),
    job_title: z3.string().trim().min(1).describe("Job title."),
    job_company: z3.string().trim().min(1).describe("Hiring company."),
    job_source: z3.string().trim().default("MCP").describe("Where the job was found."),
    action: z3.enum(["saved", "applied", "not_interested"]).describe("Tracking status to record for this job.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ job_url, job_title, job_company, job_source, action }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const user_id = ctx.getUserId();
    await supabase.from("job_actions").delete().eq("user_id", user_id).eq("job_url", job_url);
    const { data, error } = await supabase.from("job_actions").insert({ user_id, job_url, job_title, job_company, job_source, action }).select();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: `Marked "${job_title}" as ${action}.` }],
      structuredContent: { row: data?.[0] }
    };
  }
});

// src/lib/mcp/tools/untrack-job.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var untrack_job_default = defineTool4({
  name: "untrack_job",
  title: "Untrack a job",
  description: "Remove a job's saved / applied / not-interested status for the signed-in user.",
  inputSchema: {
    job_url: z4.string().url().describe("Canonical URL of the job listing to untrack.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ job_url }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("job_actions").delete().eq("user_id", ctx.getUserId()).eq("job_url", job_url).select();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: `Removed ${data?.length ?? 0} tracking record(s).` }],
      structuredContent: { removed: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/manage-job-alert.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var manage_job_alert_default = defineTool5({
  name: "manage_job_alert",
  title: "Manage daily job alert",
  description: "View or update the signed-in user's daily job alert email settings (keywords, location, enabled).",
  inputSchema: {
    operation: z5.enum(["get", "update"]).default("get").describe("Read or update the alert config."),
    enabled: z5.boolean().optional().describe("Turn the daily alert email on or off (update only)."),
    location: z5.string().trim().optional().describe("Location filter for alerts (update only)."),
    keywords: z5.array(z5.string().trim().min(1)).optional().describe("Keyword list for alerts (update only).")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ operation, enabled, location, keywords }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const user_id = ctx.getUserId();
    if (operation === "get") {
      const { data: data2, error: error2 } = await supabase.from("job_alerts").select("enabled, email, location, keywords, source_names, last_alerted_at").eq("user_id", user_id).maybeSingle();
      return error2 ? { content: [{ type: "text", text: error2.message }], isError: true } : {
        content: [{ type: "text", text: JSON.stringify(data2 ?? { configured: false }, null, 2) }],
        structuredContent: { alert: data2 ?? null }
      };
    }
    const patch = { updated_at: (/* @__PURE__ */ new Date()).toISOString() };
    if (enabled !== void 0) patch.enabled = enabled;
    if (location !== void 0) patch.location = location;
    if (keywords !== void 0) patch.keywords = keywords;
    if (Object.keys(patch).length === 1) {
      return { content: [{ type: "text", text: "Nothing to update." }], isError: true };
    }
    const { data, error } = await supabase.from("job_alerts").update(patch).eq("user_id", user_id).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.length) {
      return {
        content: [{ type: "text", text: "No alert configured yet \u2014 set one up in the app first." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data[0], null, 2) }],
      structuredContent: { alert: data[0] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ojtredjreiajjrgcwcuy";
var mcp_default = defineMcp({
  name: "mbajobscout",
  title: "MBAJOBSCOUT",
  version: "0.1.0",
  instructions: "Tools for MBAJOBSCOUT, a UK job aggregator across VC, PE, IB, consulting, S&T, investment management, tech and startups. Use `search_jobs` to find roles, `track_job` / `untrack_job` to manage the user's saved, applied and dismissed jobs, `list_tracked_jobs` to review them, and `manage_job_alert` for daily alert email settings.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_jobs_default, list_tracked_jobs_default, track_job_default, untrack_job_default, manage_job_alert_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
